### ISSUE TITLE
Activity 3.4: Extra checkbox

### ISSUE THREAD

**Issue by TanviB25** [gnowledge/gstudio#1602] opened 2017-01-28 11:32 UTC
Reference:http://103.36.84.136/invitation2clix-hindi/gcourse/course_section/57927198a6127d01f8e86a6c/5792719aa6127d01f8e86aa5/5792719aa6127d01f8e86aa7/

With reference to above url, two extra checkboxes are present.

![activity3 4](https://cloud.githubusercontent.com/assets/19238176/22396303/45711ba8-e57b-11e6-9f3d-e0dbf17378c4.png)

**Comment by udnshah** [comment] 2017-01-31 10:47
@TanviB25 This is a known bug. As currently there is no option for removing the additional check boxes we have left the check boxes.

This does not affect the course as these are review question and it is showing the what the student have learning the activity.

As it was a minor issue, it was given lower priority.

@katkamrachana  will resolve this issue soon

**Comment by katkamrachana** [comment] 2017-06-01 12:49
Duplicate of #1600

**Closed by katkamrachana** 2017-06-01 12:49 UTC
