### ISSUE TITLE
Visits gained getting incremented by 2

### ISSUE THREAD

**Issue by SatejG** [gnowledge/gstudio#1546] opened 2016-08-17 22:49 UTC
In the course platform,
For user visits gained, visits to others,(for files, notes etc.) this counters in analytics getting incremented by 2.

**Comment by katkamrachana** [comment] 2016-11-26 08:35
The root cause for this was a hyperlink in an embedded template that had `href='#'` which reloaded the entire page and eventually calling the functions twice.
This is fixed in [this](https://github.com/gnowledge/gstudio/commit/a25f2691aaf7b78678bba073d534a5e8d0b0cab1#diff-e16615ad2b6ec4d4248694fd4a312c18) commit by @kedar2a

**Closed by katkamrachana** 2016-11-26 08:35 UTC
