### ISSUE TITLE
group data_dump and group restore script bugs

### ISSUE THREAD

**Issue by udnshah** [gnowledge/gstudio#1527] opened 2016-07-19 13:51 UTC
group data_dump and group restore script does not restore the interaction settings and help pages. Also the group start date, end date and enrollment dates are not getting set that are set in original group

**Comment by katkamrachana** [comment] 2016-11-26 08:22
The start and end dates of course and enrollment duration bug can be fixed by running fixed_nodes.py as mentioned in the [dump-restore documentation Step 8](https://github.com/gnowledge/gstudio/blob/master/doc/developer/Dump-Restore.org).
Closing this issue as it is a duplicate of issue #1516 w.r.t interactions settings and help pages bug.

**Closed by katkamrachana** 2016-11-26 08:22 UTC
